# Generated by Django 5.1.4 on 2025-04-02 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('formularios', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compartido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formulario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compartidos', to='formularios.formulario')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formularios_compartidos', to='usuarios.usuario')),
            ],
            options={
                'unique_together': {('formulario', 'usuario')},
            },
        ),
    ]
